# Hardware Decoding
vo=gpu-next
hwdec=vulkan,vaapi

# Use high quality profile
profile=high-quality
video-sync=display-resample
interpolation
tscale=oversample

# Audio
alang=ja,en,tr

# Subtitles
slang=en,tr
sub-auto=fuzzy
embeddedfonts=yes

# Real filesystems use case sensitive file/directory names
sub-file-paths=ass:srt:sub:Sub:subs:Subs:subtitles:Subtitles
