#! /usr/bin/env bash

# $1 network namespace name
NETNS_NAME="${1}"
shift

if ! ip netns list | grep -q "${NETNS_NAME}"; then
    echo "Error: Namespace ${NETNS_NAME} not found."
    exit 1
fi

exec ip netns exec "${NETNS_NAME}" sudo -u "${SUDO_USER}" WAYLAND_DISPLAY="${WAYLAND_DISPLAY}" XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR}" "${@}"
