#!/usr/bin/env bash

# SPDX-License-Identifier: GPL-3.0-only
# vim: set ts=8 sw=8 sts=4 noet:
#
# Simple wrapper script around cp for copying same file to multiple destinations
#
# Author: Mehmet Akif TASOVA <makiftasova@gmail.com>
#
# Usage:
#   cpmulti SOURCE DEST1 [DEST2 [DEST3 ...]]
#

function usage {
	echo 'cpmulti SOURCE DEST1 [DEST2 [DEST3 ...]]'
}

function cpmulti {
	for f in "${@:2}"; do
		cp "${1}" "${f}"
	done
}

if [ "${#}" -lt 2 ]; then
	usage "${0}"
	exit 255
fi

cpmulti "$@"
