#!/bin/sh

# Setup some wayland related variables
export _JAVA_AWT_WM_NONREPARENTING='1'
export GDK_BACKEND='wayland'
export XDG_SESSION_TYPE='wayland'
export XCURSOR_THEME='Adwaita'
export XDG_CURRENT_DESKTOP='sway'

# Setup XDG Base Directory variables
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"
export XDG_DESKTOP_DIR="${HOME}/Desktop"
export XDG_DOWNLOAD_DIR="${HOME}/Downloads"
export XDG_DOCUMENTS_DIR="${HOME}/Documents"
export XDG_MUSIC_DIR="${HOME}/Music"
export XDG_PICTURES_DIR="${HOME}/Pictures"
export XDG_VIDEOS_DIR="${HOME}/Videos"

# Make sure XDG Base Directory directories are created
mkdir -p "${XDG_CONFIG_HOME}"
mkdir -p "${XDG_CACHE_HOME}"
mkdir -p "${XDG_DATA_HOME}"
mkdir -p "${XDG_STATE_HOME}"
mkdir -p "${XDG_DESKTOP_DIR}"
mkdir -p "${XDG_DOWNLOAD_DIR}"
mkdir -p "${XDG_DOCUMENTS_DIR}"
mkdir -p "${XDG_MUSIC_DIR}"
mkdir -p "${XDG_PICTURES_DIR}"
mkdir -p "${XDG_VIDEOS_DIR}"

# Setup XDG_RUNTIME_DIR
if [ -z "${XDG_RUNTIME_DIR}" ]; then
	XDG_RUNTIME_DIR="/tmp/runtime/${USER}"
	mkdir -p "${XDG_RUNTIME_DIR}"
	export XDG_RUNTIME_DIR
fi

# If $SWAY_DEBUG is non-empty string, save sway's logs to a file.
# If SWAY_DEBUG_FILE is non-empty string use path provided in it for saving sway
# logs.
# By default, logs are put into file at $XDG_CACHE_HOME/sway_YYYYmmdd_HHMMSS.log
# file.
if [ -n "${SWAY_DEBUG}" ]; then
	__SWAY_DEBUG_FILE="$XDG_CACHE_HOME/sway_$(date +%Y%m%d_%H%M%S).log"
	if [ -n "${SWAY_DEBUG_FILE}" ]; then
		__SWAY_DEBUG_FILE="${SWAY_DEBUG_FILE}"
	fi

	echo "Using ${__SWAY_DEBUG_FILE} for sway logs"
	sway --debug 2>"${__SWAY_DEBUG_FILE}"
else
	sway
fi
