#!/bin/sh

# Setup some wayland related variables
export _JAVA_AWT_WM_NONREPARENTING='1'
export GDK_BACKEND='wayland'
export XDG_SESSION_TYPE='wayland'
export XCURSOR_THEME='Adwaita'
export XDG_CURRENT_DESKTOP='sway'

# Setup XDG Base Directory variables
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_DESKTOP_DIR="${HOME}/Desktop"
export XDG_DOWNLOAD_DIR="${HOME}/Downloads"
export XDG_DOCUMENTS_DIR="${HOME}/Documents"
export XDG_MUSIC_DIR="${HOME}/Music"
export XDG_PICTURES_DIR="${HOME}/Pictures"
export XDG_VIDEOS_DIR="${HOME}/Videos"

# Make sure XDG Base Directory directories are created
mkdir -p "${XDG_CONFIG_HOME}"
mkdir -p "${XDG_CACHE_HOME}"
mkdir -p "${XDG_DATA_HOME}"
mkdir -p "${XDG_DESKTOP_DIR}"
mkdir -p "${XDG_DOWNLOAD_DIR}"
mkdir -p "${XDG_DOCUMENTS_DIR}"
mkdir -p "${XDG_MUSIC_DIR}"
mkdir -p "${XDG_PICTURES_DIR}"
mkdir -p "${XDG_VIDEOS_DIR}"

# Setup XDG_RUNTIME_DIR
if [ -z "${XDG_RUNTIME_DIR}" ]; then
	XDG_RUNTIME_DIR="/tmp/runtime/${USER}"
	mkdir -p "${XDG_RUNTIME_DIR}"
	export XDG_RUNTIME_DIR
fi

exec dbus-run-session -- sway
