# shellcheck disable=SC2148
# Do not warn for "unknown shell" since this file is main config file for zsh

# prevent duplicate entries in zsh history
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS

# use fcntl locks when possible
setopt HIST_FCNTL_LOCK

# Make sure zsh does not exit on EOF (CTRL+D in most terminal emulators)
# if zsh is running in tmux session
if [ -n "${TMUX}" ]; then
	setopt IGNORE_EOF
fi

# set config directories
export ZSH_CONFIG_HOME="${HOME}/.config/zsh"
export ZSH_CACHE_HOME="${HOME}/.cache/zsh"
export ZSH_CONFIG_LOCAL_HOME="${HOME}/.local/config/zsh"
export ZSH_COMPDUMP="${ZSH_CACHE_HOME}/.zcompdump-${HOST}-${ZSH_VERSION}"

# make sure ZSH_CACHE_HOME directory exists
if ! [ -d "${ZSH_CACHE_HOME}" ]; then
    mkdir -p "${ZSH_CACHE_HOME}"
fi

# If you come from bash you might have to change your $PATH.
# shellcheck source=/dev/null
[ -f "${ZSH_CONFIG_HOME}/env" ] && source "${ZSH_CONFIG_HOME}/env"

#zstyle ':completion:*' special-dirs true
# shellcheck disable=SC2016 # shellcheck does not support zsh thus disabling suggestion
zstyle -e ':completion:*' special-dirs '[[ $PREFIX = (../)#(|.|..) ]] && reply=(..)'

# Path to your oh-my-zsh installation.
export ZSH=${HOME}/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# shellcheck disable=SC2034  # Unused variables left for readability
ZSH_THEME="fino-time"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=7

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# shellcheck disable=SC2034  # Unused variables left for readability
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# shellcheck disable=SC2034  # Unused variables left for readability
plugins=(
	fzf
	gitfast
	gitignore
	rust
	vagrant
	term_tab
	zsh-autosuggestions
	zsh-syntax-highlighting
)

# Some other useful plugins:
# git-flow
# gitfast

# override generic oh-my-zsh config with local one if found.
# shellcheck source=/dev/null
[ -f "${ZSH_CONFIG_LOCAL_HOME}/ohmyzshrc" ] && source "${ZSH_CONFIG_LOCAL_HOME}/ohmyzshrc"

# shellcheck source=/dev/null
source "${ZSH}/oh-my-zsh.sh"

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export LC_TIME=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='vim'
# fi
export EDITOR='nvim'
export DIFFPROG='nvim -d'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
export SSH_KEY_PATH="${HOME}/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconfig='$EDITOR ~/.zshrc'
alias ohmyzsh='$EDITOR ~/.oh-my-zsh'

# [ -f /etc/environment ] && source /etc/environment
#source ~/.profile

# shellcheck source=/dev/null
[ -f "${ZSH_CONFIG_HOME}/utils" ] && source "${ZSH_CONFIG_HOME}/utils"
# shellcheck source=/dev/null
[ -f "${ZSH_CONFIG_HOME}/funcs" ] && source "${ZSH_CONFIG_HOME}/funcs"
# shellcheck source=/dev/null
[ -f "${ZSH_CONFIG_HOME}/aliases" ] && source "${ZSH_CONFIG_HOME}/aliases"

# if swaywm is installed and we are running from tty1, start swaywm
sway_bin="$(command -v sway-run)"
if [ -z "${sway_bin}" ]; then
	sway_bin="$(command -v sway)"
fi
if [ -n "${sway_bin}" ] && [ "$(tty)" = '/dev/tty1' ]; then
	exec "${sway_bin}"
fi
unset sway_bin
